server:
  address: 0.0.0.0
  forward-headers-strategy: framework

  servlet:
    session:
      timeout: 15m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: filmdome
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    open-in-view: true

logging:
  file:
    name: logs/webserver.log

  level:
    root: INFO

    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.engine.transaction.jta.platform.internal: ERROR

    org.springframework.orm.jpa: WARN
    org.springframework.data.jpa: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN

    org.thymeleaf: ERROR

  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 30
      total-size-cap: 500MB
      file-name-pattern: logs/webserver.%d{yyyy-MM-dd}.%i.log

tmdb:
  api:
    key: ${TMDB_API_KEY}

  access:
    token: ${TMDB_ACCESS_TOKEN}